{
  appendOutput("Error: Debugger could not be resumed after a breakpoint was hit.");
}
